#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/unistd.h>

//The format of data generated by gensort is 100B per record, and each record has first 10 bytes as the real distict value, and the rest as 
//record ID and some tabs, we only need to compare the first 10 values
//So we set the struct below to define each record and sepeate the real value for easily comparison
struct arg {
    char val[10];
    char id[90];
};
struct arg *readFile(FILE *fp);
void mergeFile(long, long, long);

int main(int argc, const char * argv[]) {
    
    mergeFile(atol(argv[1]), atol(argv[2]), atol(argv[3]));
    
    return 0;
}

struct arg *readFile(FILE *fp) {

char *str = malloc(100);
//read file to string
fread(str, 100, 1, fp);
struct arg *rec = malloc(100);
//read srting to gensort record with compatible formart
memcpy(rec->val, str, 10);
memcpy(rec->id, str+12, 90);
    
    free(str);
    
    return rec;
}

void mergeFile(long fileid, long num_file, long chunkid) {

    char buffer[20];

    snprintf(buffer,20, "%ld", (chunkid+1) * (-fileid));
    FILE *fp1 = fopen(buffer, "r");

// get the size of the data file 1
    fseek(fp1, 0L, SEEK_END);
    double length1=ftell(fp1);
    fseek(fp1, 0L, SEEK_SET);

    snprintf(buffer,20, "%ld", (chunkid+2) * (-fileid));

    FILE *fp2 = fopen(buffer, "r");

// get the size of the data file 2
    fseek(fp2, 0L, SEEK_END);
    double length2=ftell(fp2);
    fseek(fp2, 0L, SEEK_SET);

    snprintf(buffer,20, "%ld", (num_file+1) * (fileid));
    FILE *fp3 = fopen(buffer, "w+");

//read file 1
    char *str1 = malloc(100);
    fread(str1, 100, 1, fp1);
    struct arg *rec1 = malloc(100);
 
    memcpy(rec1->val, str1, 10);
    memcpy(rec1->id, str1+12, 90); 

//read file 2
    char *str2 = malloc(100);
    fread(str2, 100, 1, fp2);
    struct arg *rec2 = malloc(100);

    memcpy(rec2->val, str2, 10); 
    memcpy(rec2->id, str2+12, 90);
//define number of records in file 1 and file 2    
    long count1 = 0;
    long count2 = 0;
    while(1) {
//compare firest ten values of the two records between file 1 and file 2, and store the smaller one to the third file
        if (strcmp(rec1->val, rec2->val) <= 0) {

            fprintf(fp3, "%.10s  %s", rec1->val, rec1->id);
            rec1 = readFile(fp1);
            count1++;
            if(count1 >= length1/100)
               break;
        }

        else
        {

            fprintf(fp3, "%.10s  %s", rec2->val, rec2->id);
            rec2 = readFile(fp2);
            count2++;
            if(count2 >= length2/100)
                break;
   }
    }

// store the remaining of records in file 1 and file 2 to the third file accordingly
 while (count1 < length1/100) {
       rec1 = readFile(fp1);
if(strlen(rec1->val) > 9){
fprintf(fp3, "%.10s  %s", rec1->val, rec1->id);}
        count1++;
    }

    while (count2 < length2/100) {
        rec2 = readFile(fp2);
if(strlen(rec2->val) > 9){
fprintf(fp3, "%.10s  %s", rec2->val, rec2->id);
}
        count2++;
    }

    fclose(fp1);
    fclose(fp2);   
    fclose(fp3);
//after files merged, remove original chunks    
snprintf(buffer, 20, "%ld", (chunkid+1) * (-fileid));
unlink(buffer);
snprintf(buffer, 20, "%ld", (chunkid+2) * (-fileid));
unlink(buffer);
}



