#include <stdlib.h>
#include <stdio.h>
#include <string.h>

//The format of data generated by gensort is 100B per record, and each record has first 10 bytes as the real distict value, and the rest as 
//record ID and some tabs, we only need to compare the first 10 values
//So we set the struct below to define each record and sepeate the real value for easily comparison
struct arg {
    char val[10];
    char id[90];
};

void readChunk(long num_chunks);
void mergeSort(struct arg rec[], long low, long high, long length);
void merge(struct arg arr[],long low,long mid,long high, long length);


int main(int argc, const char * argv[]) {
    
    readChunk(atoi(argv[1]));
    
    return 0;
}

//read chunk records into file and use merge sort to sort
void readChunk(long num_chunks) {
	
	char buffer[20];
    
    snprintf(buffer, 20, "%ld", num_chunks+1);
    
    FILE *newfp = fopen(buffer, "r+");

// get the size of the data file
    fseek(newfp, 0L, SEEK_END);
    double length=ftell(newfp);
    fseek(newfp, 0L, SEEK_SET);
    long num_rec = length/100;

//copy records into file newfp
    struct arg *rec = malloc(length);
    char *str1 = malloc(100);
	long i;
    for (i=0; i<num_rec; i++) {
    fread(str1, 100, 1, newfp);
  
    memcpy(rec[i].val, str1, 10);
    memcpy(rec[i].id, str1+12, 90);

    }
    
    fclose(newfp);
//run merge sort
    mergeSort(rec, 0, num_rec-1, length);

    snprintf(buffer,20, "%ld", num_chunks+1);
    newfp = fopen(buffer, "w");

    for (i=0; i<num_rec; i++)
    fprintf(newfp, "%.10s  %s", rec[i].val, rec[i].id);
  
    fclose(newfp);
}



void mergeSort(struct arg rec[], long low, long high, long length){
    if (low < high)  {

        long mid = (low+high)/2;
        mergeSort(rec, low, mid, length);
        mergeSort(rec, mid+1, high, length);        
        merge(rec, low, mid, high, length);
    }
}


void merge(struct arg arr[],long low,long mid,long high, long length) {
    long k=low;
    struct arg *tmp = malloc(length);
  
    while(k<=high){
	strncpy(tmp[k].val,arr[k].val,10);
	strncpy(tmp[k].id,arr[k].id,90);
	k++;
    }
  
    long m=mid+1;
    long i=low;
    long j=low;
    while(j<=mid&&m<=high){
	if (strcmp(tmp[j].val,tmp[m].val) <= 0) {
            strncpy(arr[i].val, tmp[j].val, 10);
            strncpy(arr[i].id, tmp[j].id, 90);
            j++;
        }
	else{
            strncpy(arr[i].val, tmp[m].val, 10);
            strncpy(arr[i].id, tmp[m].id, 90);
    	    m++;
	}
        i++;
    }
    
    k=j;
    while(j<=mid&&k<=mid){
	strncpy(arr[i].val,tmp[k].val,10);
	strncpy(arr[i].id,tmp[k].id,90);
	i++;
	k++;
    }

    k=m;
    while(j>mid&&k<=high){
        strncpy(arr[i].val,tmp[k].val,10);
	strncpy(arr[i].id,tmp[k].id,90);
	i++;
	k++;
    }    
}




